### PR TITLE
Fix datastore to bigquery

### PR DESCRIPTION
**Pull request by vbambuch**
- add JSONPath attribute
- use `withSchema` in `WriteBigQuery` job part

### CODE REVIEW

**Comment by vbambuch** [comment]
@googlebot I signed it!

**Comment by vbambuch** [comment]
Okey...and what should I do? Do I need to make any other changes before you review it? 🤔

**Comment by sabhyankar** [comment]
Thanks for the PR @vbambuch - Ill take a look at this shortly

**Comment by vbambuch** [comment]
Great! Thank you @sabhyankar.

**Pull request closed without merging**
