### PR TITLE
Add support for Elasticsearch 8

### PR DESCRIPTION
**Pull request by Cherepushko**
This PR should fix compatibility issue with Elasticsearch 8.

### CODE REVIEW

**Comment by Cherepushko** [comment]
@suyograo @prathapreddy123

**Comment by suyograo** [comment]
@Cherepushko can you remove the code change that fixes the dot field and just keep this PR to the 8.0 compatibility fix? It will be easier to review/approve/release. The version issue is more critical than dot, which we can merge in another, separate PR

**Comment by Cherepushko** [comment]
@suyograo dot fix has been removed from this pull request but kept in different branch for future usage. Now here's only compatibility fix as well.

**Comment by suyograo** [comment]
@Cherepushko tests are still failing - did you pull latest from master?

**Comment by Cherepushko** [comment]
> @Cherepushko tests are still failing - did you pull latest from master?

@suyograo This branch has been rebased with main branch. I'm trying to investigate this.

**Comment by Cherepushko** [comment]
@suyograo

> java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/JavaFormatterOptions has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

The reason of failing checks is the compatibility issue with Java 8. We use Java 8 in the project, but spotless checks can be run with JVM 11 and higher (checked locally).

[Google Java Format 1.8 Release Notes](https://github.com/google/google-java-format/releases/tag/google-java-format-1.8)

**Comment by suyograo** [comment]
@an2x could we please get some 👀 on this PR? it is blocking users from using ES 8.x and we've seen several issues raised on this. not sure what to do with the test failures as @Cherepushko explained the Java 11 vs Java 8 differences. thanks!

**Review by an2x — APPROVED** [review]

**Comment by an2x** [comment]
The PR looks good to me, but the project build is currently broken (Java PR / Build and Unit Tests tasks are failing). I'm working on fixing those. Once done (ETA is tomorrow), I'll post an update here as well. Please pull the newest version from main and update the PR after that.

**Comment by suyograo** [comment]
thanks a ton @an2x

**Comment by Cherepushko** [comment]
@suyograo @an2x The branch was rebased, now all checks are passed.

**Review by an2x — APPROVED** [review]

**Comment by suyograo** [comment]
@an2x is there an action on us to merge this?

**Comment by an2x** [comment]
> @an2x is there an action on us to merge this?

No action required, it should be merged automatically (ETA: today, not immediately as it has to go through additional internal tests).

**Comment by yerome27** [comment]
Could you tell us when it will be available on GCP ? Despite having the change merged I'm still getting the same version control error on the pubsub_to_elasticsearch template. I guess the behaviour is the same on any dataflow template that has elasticsearch as destination.

**Comment by damianhw** [comment]
Echoing last comment. When can we create a dataflow job with this as default version?

**Comment by an2x** [comment]
@Cherepushko I noticed there is this additional check [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/07b0e921eea8069691ea74ac81e66f5b1ada3e2b/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java#L1552) that won't accept version 8. Does it need to be updated too?

**Comment by jeffxf** [comment]
> @Cherepushko I noticed there is this additional check [here](https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/07b0e921eea8069691ea74ac81e66f5b1ada3e2b/v2/elasticsearch-common/src/main/java/com/google/cloud/teleport/v2/elasticsearch/utils/ElasticsearchIO.java#L1552) that won't accept version 8. Does it need to be updated too?

I'm pretty sure that does need to be updated. I just reopened this PR which updates it: https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/369.

**Comment by jeffxf** [comment]
I should add that there are still references to `backendVersion` in 29 places. It makes sense to refactor and remove the precondition entirely but are you willing to unblock this by merging #369 first?

**Comment by damianhw** [comment]
> Templates releases are cut every Monday, and take ~7 days to rollout to GCP. This change was included in the [2022-05-16-00_RC00](https://github.com/GoogleCloudPlatform/DataflowTemplates/releases/tag/2022-05-16-00_RC00) release, started on May 16th and expected to finish rolling out on May 22nd, with different regions updated one by one. For example, us-west3 should've already been updated, so if you create a new job using the Elasticsearch template in that region it should pick up the update.

Is there a way to know instead of just creating a new job and hoping it is there?

**Comment by yerome27** [comment]
The roll out must have happen now according to @an2x answer. Yet, i'm still getting the same issue with the version error. It probably still need #369 to work properly.

**Comment by deshrajxseed** [comment]
@Cherepushko any update here.?

**Pull request merged**
