### PR TITLE
import neo4j RM changes

### PR DESCRIPTION
**Pull request by Polber**

### CODE REVIEW

**Review by fbiville — APPROVED** [review]

**Comment by fbiville** [comment]
Any updates on this?

**Comment by Polber** [comment]
@fbiville Running the IT's with the imported resource manager still fails... not sure if there is something I am missing, but it may not be worth investing too much time into this PR since Beam 2.57 will be released in the next couple weeks

**Comment by fbiville** [comment]
@Polber I realize now that I implement the API for the database wait option completely backwards 🤦 
https://github.com/Polber/DataflowTemplates/pull/20 attempts to fix that.

**Comment by fbiville** [comment]
The CI failure seems unrelated.

**Comment by Polber** [comment]
@fbiville apologies for the delay. I went ahead and refactored to use the RM from Beam 2.57 since the repo has now been updated to that version. Let me know if the changes look good (tests are passing) and I can get this merged.

**Comment by fbiville** [comment]
@Polber unfortunately, the fixes I pushed earlier are still needed...
the Neo4jResourceManager in Beam uses the wait options for static databases where it should have been for dynamic databases (and this is completely on me, I really have implemented the opposite of what I should have)
If you can reinstate the changes in the PR I sent to your fork, that'd be great.
I can also recreate the PR from the current state if that's easier for you

**Pull request closed without merging**
