### PR TITLE
replaced property gcpPubsubTopic with gcpPubsubTopicPrefix

### PR DESCRIPTION
**Pull request by skumarlabs**
Replaced property name `gcpPubsubTopic `with `gcpPubsubTopicPrefix `in `DataflowTemplates/v2/cdc-parent/cdc-embedded-connector/src/main/resources/dataflow_cdc.properties`

Fixes the PubSub topic name being null as App.java was not able to get `gcpPubsubTopicPrefix `value

### CODE REVIEW

**Comment by skumarlabs** [comment]
@googlebot I signed it!

**Comment by pabloem** [comment]
I'm sorry I missed this. This LGTM.

**Comment by skumarlabs** [comment]
> I'm sorry I missed this. This LGTM.

Never mind. The change was fixed in a later commit.

**Comment by prathapreddy123** [comment]
@skumarlabs  -  Can you rebase to latest master version and resubmit the PR

**Comment by prathapreddy123** [comment]
@skumarlabs  - Can you rebase this branch to latest master?

**Comment by skumarlabs** [comment]
@prathapreddy123 done.

**Review by prathapreddy123 — APPROVED** [review]

**Pull request closed without merging**
