### PR TITLE
It

### PR DESCRIPTION
**Pull request by aksharauke**
Corrected the object name prefix to create the PubSub notifications

### CODE REVIEW

**Comment by damccorm** [comment]
It looks like tests are still failing, I think this may be due to a dependency cache issue. @Polber does that look right? If so, what do we need to do to fix this?

**Comment by aksharauke** [comment]
> It looks like tests are still failing, I think this may be due to a dependency cache issue. @Polber does that look right? If so, what do we need to do to fix this?

The problematic integration test is fixed though. The spanner-to-sourcedb has passed
[INFO] spanner-to-sourcedb ................................ SUCCESS [17:56 min]

But yeah, tests in other templates are not passing.

**Comment by damccorm** [comment]
Rerunning checks after clearing the cache

**Comment by damccorm** [comment]
Actually @aksharauke could you try pulling in the latest changes from master - looks like caching was actually just hiding the issue before, but https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1927 should fix the problem generally

**Comment by aksharauke** [comment]
> Actually @aksharauke could you try pulling in the latest changes from master - looks like caching was actually just hiding the issue before, but #1927 should fix the problem generally

This PR does not change the file affected by #1927, so just retriggering the integration tests should help I suppose?

**Comment by damccorm** [comment]
> This PR does not change the file affected by https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1927, so just retriggering the integration tests should help I suppose?

I don't think so - when you rerun IIRC GitHub will still run the rerun at the same merge commit, which won't include the change. So I think we need to pull in the change directly (or push any other change which will cause the merge commit to be recomputed)

**Comment by aksharauke** [comment]
> > This PR does not change the file affected by #1927, so just retriggering the integration tests should help I suppose?
> 
> I don't think so - when you rerun IIRC GitHub will still run the rerun at the same merge commit, which won't include the change. So I think we need to pull in the change directly (or push any other change which will cause the merge commit to be recomputed)

I see, thanks. Done, updated my branch.

**Review by shreyakhajanchi — APPROVED** [review]

**Pull request merged**
