### PR TITLE
Post sync to beam it framework

### PR DESCRIPTION
**Pull request by Abacn**

### CODE REVIEW

**Comment by Abacn** [comment]
R: @pranavbhandari24

**Review by pranavbhandari24 — APPROVED** [review]
LGTM!

**Comment by Abacn** [comment]
ah - it appears beam and template repo has different spotless rule - so need to run spotless on both side

**Comment by bvolpato** [comment]
FYI this caused actual breakages, caught in the checks https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/6250532680/job/16973504465

https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1066

**Pull request merged**
