### PR TITLE
Refactor Elasticsearch maven modules

### PR DESCRIPTION
**Pull request by Cherepushko**
Created Elasticsearch Maven module that combine old PubSub-To-Elasticsearch, BigQuery-To-Elasticsearch and Csv-To-Elasticsearch modules. Added main class to run application specified in options. Added options to pass Elastic endpoint credentials. Moved some inner classes into different .java files. Created initial hierarchy for options interfaces.
Tested on Dataflow (case PubSub to Elasticsearch). Other submodules wasn't tested.

### CODE REVIEW

**Comment by Cherepushko** [comment]
@googlebot I signed it!

**Comment by suyograo** [comment]
cc @prathapreddy123

**Comment by prathapreddy123** [comment]
@Cherepushko -  CLA process seems to be incomplete. Can you verify again based on the information [here](https://opensource.google/docs/cla/#external-contributors)

**Comment by Cherepushko** [comment]
@googlebot I signed it!

**Comment by Cherepushko** [comment]
@prathapreddy123 the issue with CLA is fixed.

**Comment by Cherepushko** [comment]
@prathapreddy123 @suyograo

**Comment by prathapreddy123** [comment]
@Cherepushko @suyograo 

Based on the latest design the module structure has been changed as shown below:

v2
├── common
├── kafka-common
 │   ├── options
 │   ├── transforms
 │   └── utils 
├── elasticsearch-common
 │   ├── options
 │   ├── transforms
 │   └── utils
├── googlecloud-to-kafka
 │   └── templates
 │       └── PubsubToKafka.java
├── googlecloud-to-elasticsearch
 │   └── templates
 │       ├── BigqueryToElasticsearch.java
 │       └── PubsubToElasticsearch.java

 Given the size of current PR, it would be helpful to break down into three smaller PR’s.

1. Build elasticsearch-common abstraction
2. Add googlecloud-to-elasticsearch module with the templates
3. Remove old modules (i.e bigquery-to-elasticsearch,csv-to-elasticsearch,pubsub-to-elasticsearch)

**Pull request closed without merging**
