### PR TITLE
Validate Beam 2.60.0rc1

### PR DESCRIPTION
**Pull request by Abacn**

### CODE REVIEW

**Comment by Abacn** [comment]
- Java PR failing Yaml template tests:

```
YAMLTemplateIT.testSimpleCompositeSpec

value of    : listArtifacts(...).size()
expected    : 1
but was     : 0
iterable was: []

-----

value of    : listArtifacts(...).size()
expected    : 1
but was     : 0
iterable was: []
```

see https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1929/checks?check_run_id=31422266417 (PythonUDF test failure were expected)


- Kafka PR passed

- Spanner PR failed:

https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1929/checks?check_run_id=31432253000

```
DataStreamToSpannerIT.testDataStreamOracleToSpannerJsonStaging

DataStreamToSpannerIT.testDataStreamOracleToSpannerStaging
```

both due to

```
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: CPU overload detected on server hosting z114_3021435 for Isolation Key [/AS/u/]. Failing-fast.
```

**Comment by Abacn** [comment]
also, found the job id for "testSimpleCompositeSpec" in log: `2024-10-11_08_47_47-15796645599809192690` is actually a Beam 2.59.0 job:

image

looks like changing `beam-python.version` following https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/contributor-docs/maintainers-guide.md is no longer effective. Is it related to #1871 ? iiuc this raices burden to upgrade Beam version.

**Comment by damccorm** [comment]
> looks like changing beam-python.version following https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/contributor-docs/maintainers-guide.md is no longer effective. Is it related to https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1871 ? iiuc this raices burden to upgrade Beam version.

Yeah, I'll update the maintainers guide. Because of the new security requirement to always install dependencies from sources with hashes, we need to store versions in requirements.txt itself. So the new path should be:

1) Update `beam-python.version`
2) Update the beam versions in all `*_base_*.requirements.txt` files mentioned in https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/main/python/generate_all_dependencies.sh
3) Run `sh python/generate_all_dependencies.sh` from the root of the repo

**Comment by damccorm** [comment]
https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1936

**Pull request closed without merging**
