### PR TITLE
updating syndeo template to proper dependencies

### PR DESCRIPTION
**Pull request by pabloem**
To use the proper kafka urn and proper snapshot dependencies

### CODE REVIEW

**Comment by pabloem** [comment]
r: @manavgarg

**Review by manavgarg — DISMISSED** [review]
LGTM

**Comment by Abacn** [comment]
Hi @pabloem I also opened #604; it would be nice to integrate that PR here. The problem is that the last Beam 2.46.0-SNAPSHOT has breaking changes but the fix is in 2.47.0-SNAPSHOT due to release cut

**Comment by pabloem** [comment]
okay let's see...

**Comment by pabloem** [comment]
fixing up...

**Comment by pabloem** [comment]
finally passing I think : )

**Pull request merged**
