### PR TITLE
[Fix Bug 1252] Cloud_Spanner_to_GCS_Avro failing on genarated fields

### PR DESCRIPTION
**Pull request by niklas1244**
Generated Fields are not present in the Struct row but present in the this.fields stream.
Iterating over the this.fields stream must therefore be restricted to non-generated fields.

Fixing Issue https://github.com/GoogleCloudPlatform/DataflowTemplates/issues/1252#issue-2070230960
Thanks to @hni42!

### CODE REVIEW

**Comment by niklas1244** [comment]
@bvolpato could you rerun the pipeline as maintainer :)

**Comment by niklas1244** [comment]
@bvolpato :)

**Review by bvolpato — APPROVED** [review]
Thanks, this LGTM!

**Comment by bvolpato** [comment]
FYI @darshan-sj, sending this internally for your LGTM

**Pull request merged**
