### PR TITLE
Add PubsubToNewRelic template

### PR DESCRIPTION
**Pull request by jsubirat**
## Description
The following PR adds a new Dataflow template which takes log records from a PubSub subscription and forwards them to New Relic using the HTTP Logs API.

**NOTE: ** it seems that when we ran `mvn spotless:apply`, as suggested in the `README.md`, other non-related files were also formatted (only applies to white spaces/lines).

## Tests
- Unitary tests have been provided for relevant classes.
- Several full end-to-end integration tests (only mocking PubSub and using MockServer to capture the emitted HTTP requests) can be found in `NewRelicPipelineTest`.

### CODE REVIEW

**Comment by jsubirat** [comment]
@googlebot I signed it!

**Comment by jsubirat** [comment]
@googlebot I signed it!

**Comment by jodstrcil** [comment]
@googlebot I signed it!

**Comment by noly** [comment]
@googlebot I signed it!

**Pull request closed without merging**
