### PR TITLE
Fix BigQueryDynamicDestination to properly fetch TableRow field names

### PR DESCRIPTION
**Pull request by ahmedabu98**
In our `BigQueryDynamicDestination` classes, we fetch a TableRow's field names to dynamically create a TableSchema. We do this by calling `TableRow::getF()`, but this is an unreliable method that can return null and causing this error:

```
Caused by: java.lang.NullPointerException
	at com.google.cloud.teleport.v2.templates.BigQueryDynamicConverters$BigQueryDynamicDestination.getSchema(BigQueryDynamicConverters.java:152)
	at com.google.cloud.teleport.v2.templates.BigQueryDynamicConverters$BigQueryDynamicDestination.getSchema(BigQueryDynamicConverters.java:120)
	at org.apache.beam.sdk.io.gcp.bigquery.DynamicDestinationsHelpers$DelegatingDynamicDestinations.getSchema(DynamicDestinationsHelpers.java:178)
	at org.apache.beam.sdk.io.gcp.bigquery.StorageApiDynamicDestinationsTableRow.getSchema(StorageApiDynamicDestinationsTableRow.java:36)
	at org.apache.beam.sdk.io.gcp.bigquery.StorageApiDynamicDestinationsTableRow$TableRowConverter.<init>(StorageApiDynamicDestinationsTableRow.java:95)
	at org.apache.beam.sdk.io.gcp.bigquery.StorageApiDynamicDestinationsTableRow.getMessageConverter(StorageApiDynamicDestinationsTableRow.java:73)
	at org.apache.beam.sdk.io.gcp.bigquery.TwoLevelMessageConverterCache.lambda$get$0(TwoLevelMessageConverterCache.java:72)
```
This especially affects writing with Storage API because getSchema() is called to encode TableRows before sending to BQ. 

TableRow is ultimately a map, so we can look at the keySet instead.

Internal bugs: 321906363 and 319648178

### CODE REVIEW

**Comment by ahmedabu98** [comment]
R: @Abacn

**Comment by Abacn** [comment]
Tests not running: `Unknown lifecycle phase "". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal>` However an earlier PR did not have the issue.

**Comment by Abacn** [comment]
@ahmedabu98 could you please trying to rebase your branch onto latest `main` and see if tests could run?

**Comment by ahmedabu98** [comment]
Rebased but now it's failing due to a change in cl/603288378

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project spanner-change-streams-to-sharded-file-sink: Compilation failure: Compilation failure: 
Error:  /home/runner/actions-runner/_work/DataflowTemplates/DataflowTemplates/v2/spanner-change-streams-to-sharded-file-sink/src/main/java/com/google/cloud/teleport/v2/templates/utils/ShardIdFetcherImpl.java:[99,3] method does not override or implement a method from a supertype
Error:  /home/runner/actions-runner/_work/DataflowTemplates/DataflowTemplates/v2/spanner-change-streams-to-sharded-file-sink/src/main/java/com/google/cloud/teleport/v2/templates/transforms/AssignShardIdFn.java:[269,21] cannot find symbol
Error:    symbol:   method init(java.lang.String)
Error:    location: variable shardFetcher of type com.google.cloud.teleport.v2.spanner.utils.IShardIdFetcher
```

**Comment by ahmedabu98** [comment]
@Abacn this is passing now, can you re-approve this PR?

**Review by Abacn — APPROVED** [review]

**Pull request merged**
