### PR TITLE
Upgrade to Beam 2.59.0

### PR DESCRIPTION
**Pull request by Abacn**

### CODE REVIEW

**Comment by Abacn** [comment]
3 failing tests:

- ExportPipelineIT.testSpannerToGCSAvroStaging - Caused by: com.google.cloud.spanner.SpannerException: FAILED_PRECONDITION: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Feature FULL_TEXT_SEARCH is not available to Instance projects/cloud-teleport-testing/instances/teleport, in Edition EDITION_UNSPECIFIED. The minimum required Edition for this feature is ENTERPRISE. Please refer documentation for additional information.

this is also failing on main branch. It breaks often in general: #1807

- BigtableChangeStreamsToGcsIT.testSingleMutationBigtableRowAvroWithStartTimeE2E and KafkaToBigQueryFlexAvroIT.testKafkaToBigQueryBinarySerializationErrorWithDLQ


random tests failing due due to intermittent gcs staging issue

```
[Error] Staged package commons-compress-1.22-U9BKDvxyI7rsqjA71dKY6wYA5rgrQHb5zs1Vi5e6dgs.jar at location 'gs://dataflow-staging-us-central1-269744978479/staging/commons-compress-1.22-U9BKDvxyI7rsqjA71dKY6wYA5rgrQHb5zs1Vi5e6dgs.jar' is inaccessible.

[Error] Staged package logback-core-1.2.13-B7FYb68iDAWCHQ8-2OLkF-IUyD9AZB926KkLE0wx_2s.jar at location 'gs://dataflow-staging-us-central1-269744978479/staging/logback-core-1.2.13-B7FYb68iDAWCHQ8-2OLkF-IUyD9AZB926KkLE0wx_2s.jar' is inaccessible.

Workflow failed. Causes: One or more access checks for temp location or staged files failed. Please refer to other error messages for details. For more information on security and permissions, please see https://cloud.google.com/dataflow/security-and-permissions.
```

I've seen random tests failing occassionally due to this reason, likely there is some racing condition of two tests staging same artifact at the same time. Retry may fix

**Comment by Abacn** [comment]
spanner PR workflow passed - https://github.com/GoogleCloudPlatform/DataflowTemplates/actions/runs/10858417210

1 test failed on second run of java-pr - `ExportPipelineIT.testSpannerToGCSAvroStaging`

**Comment by Abacn** [comment]
R: @Polber @lostluck

**Review by lostluck — APPROVED** [review]
Agreed the failures seem to be unrelated flakes.

**Comment by Abacn** [comment]
same on third run, ExportPipelineIT.testSpannerToGCSAvroStaging failed, merging for now

**Pull request merged**
