### PR TITLE
upgraded protobuf-java to 3.21.9 to resolve the conflicts with bigque…

### PR DESCRIPTION
**Pull request by xianhualiu**
…ry api

With protobuf-java v3.21.5, got following error when running pipeline to read data from BigQueryIO. Caused by: java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(com.google.protobuf.CodedInputStream, com.google.protobuf.ExtensionRegistryLite, int)'
	com.google.cloud.bigquery.storage.v1.ReadSession$Builder.mergeFrom(ReadSession.java:4665)

### CODE REVIEW

**Review by bvolpato — COMMENTED** [review]
I think we could bump libraries-bom to match Beam (26.1.5 for Beam 2.44.0), so we will be less likely to face these conflicts.

**Comment by bvolpato** [comment]
For the record, 3.21.9 would come automatically if using libraries-bom 26.1.5:

https://mvnrepository.com/artifact/com.google.cloud/libraries-bom/26.1.5

**Comment by xianhualiu** [comment]
> For the record, 3.21.9 would come automatically if using libraries-bom 26.1.5:
> 
> https://mvnrepository.com/artifact/com.google.cloud/libraries-bom/26.1.5

Will try with libraries-bom/26.1.5.

**Comment by xianhualiu** [comment]
close this one and will recreate one with cleaned changes.

**Pull request closed without merging**
