### PR TITLE
Removed deprecated Elasticsearch modules

### PR DESCRIPTION
**Pull request by Cherepushko**
Elasticsearch templates have been refactored and moved to Googlecloud-to-elasticsearch module [in PR 265](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/265). This pull request removes previous implementation of the templates.

### CODE REVIEW

**Comment by Cherepushko** [comment]
@prathapreddy123 @an2x @suyograo

**Comment by suyograo** [comment]
@Cherepushko can you add a description (removing it because we refactored it) and link to the previous PRs we merged?

**Comment by Cherepushko** [comment]
> @Cherepushko can you add a description (removing it because we refactored it) and link to the previous PRs we merged?

Sure, now description is updated.

**Comment by suyograo** [comment]
@Cherepushko can you rebase please?

**Comment by Cherepushko** [comment]
@prathapreddy123 @suyograo 
The branch is rebased.

**Review by prathapreddy123 — CHANGES_REQUESTED** [review]
We should also remove the elastic search specific classes  from common module as these will be handled inside elasticsearch-common module.  For e.g:
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/common/src/main/java/com/google/cloud/teleport/v2/transforms/ElasticsearchTransforms.java

Remove beam-sdks-java-io-elasticsearch dependency from 
https://github.com/GoogleCloudPlatform/DataflowTemplates/blob/master/v2/common/pom.xml#L107
and add to elasticsearch-common module

**Comment by Cherepushko** [comment]
@prathapreddy123
Removed ElasticsearchTransforms.
Removed beam-sdks-java-io-elasticsearch dependency from common and added it to elasticsearch-common.
ValueExtractorTransform was moved to elasticsearch-common since it used only by WriteToElasticsearch.

**Comment by prathapreddy123** [comment]
> @prathapreddy123
> Removed ElasticsearchTransforms.
> Removed beam-sdks-java-io-elasticsearch dependency from common and added it to elasticsearch-common.
> ValueExtractorTransform was moved to elasticsearch-common since it used only by WriteToElasticsearch.

Thanks @Cherepushko.  Elasticsearch-common module is missing v2/elasticsearch-common/src/test/resources/JavascriptTextTransformerTest/transform.js causing failures in ValueExtractorTransformTest.java

Can you rebase and ensure all tests are executing successfully across common, Elasticsearch-common and googlecloud-to-elasticsearch modules

**Comment by Cherepushko** [comment]
> Thanks @Cherepushko. Elasticsearch-common module is missing v2/elasticsearch-common/src/test/resources/JavascriptTextTransformerTest/transform.js and causing failures in ValueExtractorTransformTest.java
> 
> Can you rebase and ensure all tests are executing successfully across common, Elasticsearch-common and googlecloud-to-elasticsearch modules
@prathapreddy123
Done. 
But tests are stable only by running in IDE, mvn verify results a lot of failed tests sometimes, this may be produced by issues with maven config. Manual running of tests shows that all tests passed except those described [in previous PR](https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/265#issuecomment-882602374).

**Review by prathapreddy123 — APPROVED** [review]
LGTM

**Comment by zhoufek** [comment]
This PR breaks an internal build. Nothing is wrong with the PR. It's on us to fix the internal build, and I have one ready. It just needs to be approved before we can merge this PR.

I'm just mentioning this here to explain why this PR hasn't been merged yet. Hopefully, I'll be able to complete the merge today or early next week.

**Pull request merged**
