### PR TITLE
Gitactions improvements

### PR DESCRIPTION
**Pull request by Polber**
This PR provides several improvements to the existing gitactions framework

- Modularized workflows
  - There was a lot of repeated code that is now modularized to reduce duplication and provide single place to define versioning of dependency actions (other than actions/checkout which is needed in each job to make sure code is up-to-date)
- Updated dependencies
  - Numerous libraries were throwing deprecation warnings, so those have been updated
- Added scheduled workflows for Unit Tests, IT's, Load Tests and Smoke Tests
  - These workflows are scheduled to run every 6 hours, and there will be status badges added to main page to track status of the various workflows
  - They will also be able to be run as dispatch jobs using a branch passed as an input
- All workflows not run against a PR (release and scheduled workflows) will now have a site report published as an aritfact
  - The action currently used to publish a test report only works for PR runs, resulting in sifting through messy logs for release failures. The site report will now be published as an artifact and can be downloaded and run in a browser to get an organized view of the test failure(s)
- Various other cleanup to improve organization and runtime of the actions

All workflows tested on personal fork
- **Release**: https://github.com/Polber/DataflowTemplates/actions/runs/8899421405
- **Java Build**: https://github.com/Polber/DataflowTemplates/actions/runs/8899925234
- **Java Unit Tests**: https://github.com/Polber/DataflowTemplates/actions/runs/8899927780
- **Java Integration Tests**: https://github.com/Polber/DataflowTemplates/actions/runs/8899926003
- **Java Smoke Tests**: https://github.com/Polber/DataflowTemplates/actions/runs/8899926914
- **Java PR**: https://github.com/Polber/DataflowTemplates/actions/runs/8899944601 (With failing tests)
- **Java PR**: https://github.com/Polber/DataflowTemplates/actions/runs/8900110084 (With successful tests)

### CODE REVIEW

**Review by Abacn — COMMENTED** [review]
Thanks, this is a good start for infrastructure improvement

@damccorm have we decided the way to split java pr action (https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1475#discussion_r1579488300) ?

Also this large PR contains many changes to the test infrastructure. I would suggest split into smaller PRs and merge one/several a time to reduce the distraction to the developments.

Maybe dependency upgrades / optimizations can go in first (and quickly), then add new workflows, finally delete old ones

**Comment by damccorm** [comment]
> Also this large PR contains many changes to the test infrastructure. I would suggest split into smaller PRs and merge one/several a time to reduce the distraction to the developments.

Yeah, I agree with this; I like the direction of this set of changes generally, but splitting into smaller prs will make it much easier to review/revert if certain components are broken at all (this is especially important since testing CI is hard and can't be done in an obvious automatic way)

**Comment by Polber** [comment]
Fair enough. Smaller PR's TBD. Thanks

**Comment by Polber** [comment]
Opened #1519, #1520, #1521, #1522 and #1523

**Pull request closed without merging**
