### PR TITLE
Use built-in batch grouping transform

### LINKED ISSUE #1416: Google_cloud_to_neo4j v2024-03-27-00_rc00 causes unexpected increase of shuffle data processed and worker OOMs
### Related Template(s)

google_cloud_to_neo4j

### Template Version

2024-03-27-00_rc00

### What happened?

So I use `latest` version of `google_cloud_to_neo4j` pipeline and faced unexpected Dataflow job failures for the past 12 hours or so.

Initially seen error logs were quite cryptic like: 
```Error message from worker: Data channel closed, unable to receive additional data from SDK sdk-0-0```
After some debugging I assumed the actual reason for failure was OOM-ing of workers.  
However I haven't changing anything in the job itself, and it is pretty simple: export of single BQ table and writing it into neo4j via `custom_query`, thus I never experienced OOM issues before with it.

So I tried to understand what have changes and noticed template version change and, more importantly, shift of shuffle data processed from 22.66 KB in yesterday run to 10.67 GB in new, failed one.

After seeing version change of the templated, I tried switching back to `gs://dataflow-templates-us-west1/2024-03-06-00_RC00/flex/Google_Cloud_to_Neo4j` and things went back to normal in job itself, so I assume the issue was caused by new template version.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by fbiville**
Fixes #1416

### CODE REVIEW

**Review by ali-ince — APPROVED** [review]
LGTM

**Comment by ali-ince** [comment]
@liferoad I think this is ready for you to review.

**Comment by liferoad** [comment]
Can you check the failed tests? https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1418/checks?check_run_id=25124983697

**Comment by fbiville** [comment]
> Can you check the failed tests? https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1418/checks?check_run_id=25124983697

@liferoad `ConstraintsIndicesIT$Neo4j5EnterpriseIT.canResetDatabase` needs to be muted until the more recent `Neo4jResourceManager` API is available and used (maybe this branch has not been rebased in a while?)
The other test seems unrelated to the template.

**Comment by liferoad** [comment]
Can you rebase it?

**Pull request merged**
