### PR TITLE
Add Neo4j telemetry

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by bvolpato** [comment]
Hi @fbiville, can you please rebase this one?

**Comment by fbiville** [comment]
@bvolpato will do
I marked it as draft for now, since the requirements change a bit.

**Review by ali-ince — APPROVED** [review]
LGTM.

**Review by liferoad — APPROVED** [review]
Rely on the Neo4j's team to do careful reviews.

**Pull request merged**
