### PR TITLE
Fix for mutated failsafe event

### PR DESCRIPTION
**Pull request by shreyakhajanchi**

### CODE REVIEW

**Comment by manitgupta** [comment]
Can you give me the code reference of the commit where this was changed? I want to look at what happened once.

**Comment by shreyakhajanchi** [comment]
> Can you give me the code reference of the commit where this was changed? I want to look at what happened once.

https://github.com/GoogleCloudPlatform/DataflowTemplates/pull/1441/files#diff-e59a1073b170fe6c799c581e58d89d709417bb7cd1218dfd57690b0444db5911

**Review by manitgupta — DISMISSED** [review]
Thanks for the reference and the quick turnaround on the fix!

**Comment by shreyakhajanchi** [comment]
I will add an integration test as a follow up with Fks and modified schema

**Review by darshan-sj — APPROVED** [review]
LGTM. Thanks for quick fix!

**Review by manitgupta — APPROVED** [review]

**Review by bharadwaj-aditya — APPROVED** [review]
LGTM

**Pull request merged**
